### PR TITLE
Implement CTEBuilder

### PR DESCRIPTION
**Pull request by huandu**
It's a fix for #129.

### CODE REVIEW

**Comment by huandu** [comment]
@sxwebdev I add a new builder `CTETableBuilder` to build one table inside CTE. Related APIs and samples are updated to use this new builder. Looking forward to your further suggestion. Thanks.

**Comment by sxwebdev** [comment]
Works great. Am I correct in understanding that if I need to define cte aliases in the root select builder, I should use the following syntax?

```go
ctes := sqlbuilder.With(
    sqlbuilder.CTETable("table1").As(...),
    sqlbuilder.CTETable("table2").As(...),
)

sb := sqlbuilder.PostgreSQL.NewSelectBuilder().
    With(ctes).
    Select(columns...).
    From("table1 t1").
    OrderBy("t1.index").
    Asc()

sb.Join("table2 t2", "true")
```

**Comment by huandu** [comment]
Yes, you're right. And to be simpler, you can create `SelectBuilder` by calling `Select` method on `CTEBuilder`.

```go
sb := sqlbuilder.PostgreSQL.With(
    sqlbuilder.CTETable("table1").As(...),
    sqlbuilder.CTETable("table2").As(...),
).Select(columns...)
```

**Comment by sxwebdev** [comment]
I get the following error

```shell
sqlbuilder.PostgreSQL.With undefined (type sqlbuilder.Flavor has no field or method With)
```

but this example works great

```go
sb := sqlbuilder.With(
    sqlbuilder.CTETable("table1").As(...),
    sqlbuilder.CTETable("table2").As(...),
).Select(columns...)

sb.SetFlavor(sqlbuilder.PostgreSQL)
```

**Comment by huandu** [comment]
Ah, you're right. By the way, if you only use PostgreSQL in your project, you can set `DefaultFlavor` to `PostgreSQL` so that you don't need to call `SetFlavor` any more.

**Comment by sxwebdev** [comment]
thanks, everything else works fine. I'm waiting for the merge)

**Pull request merged**
